t_end: 2.0
dynamics:
  class_path: dc_motor.DCMotorDynamics
  dt: 0.001
  R: 1.0
  L: 0.01
  Ke: 0.05
  Kt: 0.05
  J: 0.001
  b: 0.001
  integrator: simulate.integrator.rk4
reference:
  class_path: simulate.reference.StepReference
  dt: 0.001
  step_value: [100.0, 0.0]
  start_time: 0.5
sensors:
  class_path: simulate.sensor.GaussianSensor
  dt: 0.001
  std_dev: 0.5
  measurement:
    class_path: dc_motor.dc_motor_measurement
estimator:
  class_path: simulate.estimator.LuenbergerObserver
  dt: 0.001
  A:
    - [-1.0, 50.0]
    - [-5.0, -100.0]
  B:
    - [0.0]
    - [100.0]
  C:
    - [1.0, 0.0]
  L:
    - [399.0]
    - [395.0]
  integrator: simulate.integrator.rk4
controller:
  class_path: simulate.controller.PIController
  dt: 0.001
  kp: [[1.0, 0.2]]
  ki: [[2.0, 0.0]]
