# mypy: ignore-errors

import marimo

__generated_with = "0.23.6"
app = marimo.App(width="medium")


@app.cell
def _():
    import sys
    from pathlib import Path

    # Add workspace root to sys.path to allow importing 'examples' package
    workspace_root = str(Path(__file__).resolve().parents[2])
    if workspace_root not in sys.path:
        sys.path.append(workspace_root)

    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np

    from simulate.simulation import Simulation
    from spacecraft.rigid_body import STATE

    return Path, STATE, Simulation, mo, np, plt


@app.cell
def _(mo):
    mo.md(r"""
    # Quadrocopter Dynamics with Modular Actuators

    This notebook demonstrates a quadrocopter simulation using the pre-built `RigidBodyDynamics` component
    and the modular `Effector` abstraction. We compose two effectors onto our rigid body:

    1. A **`FlatGravity`** effector applying constant gravitational acceleration in the inertial frame, and
    2. A **`Quadrocopter`** effector modeling 4 rotors that produce body-frame thrust and drag torque.

    We simulate a closed-loop cascaded controller tracking a position setpoint.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## Rigid Body Dynamics

    The quadrocopter's motion is governed by the standard 6-DOF Newton-Euler equations for a rigid body.

    ### Translational Dynamics
    The position $\mathbf{r}$ and velocity $\mathbf{v}$ in the inertial frame evolve according to Newton's second law:
    $$
    \dot{\mathbf{r}} = \mathbf{v} \\
    \dot{\mathbf{v}} = \frac{1}{m} \sum \mathbf{F}_{inertial}
    $$
    Where $\sum \mathbf{F}_{inertial}$ includes the body thrust rotated into the inertial frame and the constant inertial gravity vector.

    ### Rotational Dynamics
    The attitude is represented by a quaternion $\mathbf{q}$ representing the rotation from the inertial frame to the body frame. The angular velocity of the body relative to the inertial frame, expressed in the body frame, is $\boldsymbol{\omega}$. The rotational kinematics and Euler's equations are:
    $$
    \dot{\mathbf{q}} = \frac{1}{2} \mathbf{q} \otimes \begin{bmatrix} 0 \\ \boldsymbol{\omega} \end{bmatrix} \\
    \dot{\boldsymbol{\omega}} = I^{-1} \left( \sum \boldsymbol{\tau}_{body} - \boldsymbol{\omega} \times (I \boldsymbol{\omega}) \right)
    $$
    Where $I$ is the inertia matrix, and $\sum \boldsymbol{\tau}_{body}$ includes the torques generated by the individual rotors.
    """)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## Controller Architecture

    The quadrocopter is controlled using a **cascaded PID controller**. The controller is split into two loops:
    1. **Outer Loop (Position Control)**: Computes the desired thrust and attitude (pitch/roll) required to track a 3D position setpoint.
    2. **Inner Loop (Attitude Control)**: Computes the body torques required to track the desired attitude using the individual rotor thrusts.

    ### 1. Outer Loop (Position to Attitude)

    Given a position error $\mathbf{e}_p = \mathbf{r}_{ref} - \mathbf{r}$ and velocity error $\mathbf{e}_v = \mathbf{v}_{ref} - \mathbf{v}$, the desired acceleration is computed using a PD controller with gravity compensation:

    $$
    \mathbf{a}_{des} = K_{p,pos} \mathbf{e}_p + K_{d,pos} \mathbf{e}_v + \begin{bmatrix} 0 \\ 0 \\ g \end{bmatrix}
    $$

    The quadrotor generates thrust exclusively along its body $Z$-axis. Thus, we must tilt the drone such that its thrust vector aligns with $\mathbf{a}_{des}$. The total desired thrust $T_{des}$ is the projection of the desired inertial force onto the body thrust axis:

    $$
    T_{des} = m \, \mathbf{a}_{des} \cdot \mathbf{\hat{z}}_{body}
    $$

    Using the small-angle approximation for pitch ($\theta$) and roll ($\phi$), and given the current yaw angle $\psi$, the required Euler angles to achieve the horizontal accelerations $a_x$ and $a_y$ are:

    $$
    \theta_{des} = \frac{-a_x \cos\psi + a_y \sin\psi}{g} \\
    \phi_{des} = \frac{a_x \sin\psi + a_y \cos\psi}{g}
    $$
    *(Note: The signs depend on the specific coordinate and rotation sequence conventions. Here we use an active intrinsic Y-X-Z sequence where positive roll tilts the drone right and positive pitch tilts the drone backward).*

    ### 2. Inner Loop (Attitude to Torque)

    The inner loop tracks the desired Euler angles using a PD controller. Let the attitude error be $\mathbf{e}_{att} = [\phi_{des} - \phi, \theta_{des} - \theta, \psi_{des} - \psi]^T$, and the body angular velocity be $\boldsymbol{\omega} = [\omega_x, \omega_y, \omega_z]^T$.

    Because of our specific intrinsic rotation convention, the rate of change of the Euler angles has the opposite sign of the body angular velocities ($\dot{\phi} \approx -\omega_x$). Thus, the desired body torques $\boldsymbol{\tau}_{des}$ are computed as:

    $$
    \boldsymbol{\tau}_{des} = I \left( -K_{p,att} \mathbf{e}_{att} - K_{d,att} \boldsymbol{\omega} \right)
    $$

    ### 3. Rotor Mixer

    The total thrust $T_{des}$ and body torques $\boldsymbol{\tau}_{des}$ are mapped to the four individual rotor thrusts $\mathbf{f} = [f_1, f_2, f_3, f_4]^T$ using a mixer matrix $M$:

    $$
    \begin{bmatrix} T_{des} \\ \tau_x \\ \tau_y \\ \tau_z \end{bmatrix} = M \mathbf{f}
    $$

    Where the mixer matrix $M$ is explicitly defined as:

    $$
    M = \begin{bmatrix}
    1 & 1 & 1 & 1 \\
    y_1 & y_2 & y_3 & y_4 \\
    -x_1 & -x_2 & -x_3 & -x_4 \\
    -d_1 c_q & -d_2 c_q & -d_3 c_q & -d_4 c_q
    \end{bmatrix}
    $$

    Here, $(x_i, y_i)$ are the coordinates of rotor $i$ in the body frame, $d_i \in \{+1, -1\}$ is the spin direction (CCW vs CW), and $c_q$ is the aerodynamic torque-to-thrust ratio.

    The individual rotor commands are then obtained via $\mathbf{f} = M^{-1} \begin{bmatrix} T_{des} \\ \boldsymbol{\tau}_{des} \end{bmatrix}$.
    """)
    return


@app.cell
def _(Path, Simulation):
    config_path = Path(__file__).resolve().parent / "cascaded_control.yaml"
    sim = Simulation.from_yaml(config_path)
    sim.run()
    return (sim,)


@app.cell
def _(mo):
    mo.md(r"""
    ## Visualization
    """)
    return


@app.cell
def _(STATE, np, plt, sim):
    logs = sim.logger.universal_logs
    t = np.array([row["t"] for row in logs])
    x = np.array([np.asarray(row["x"]) for row in logs])
    u = np.array([np.asarray(row["u"]) for row in logs])

    fig, axes = plt.subplots(3, 1, figsize=(12, 10))

    axes[0].plot(t, x[:, STATE.r][:, 0], "r-", label="x (m)")
    axes[0].plot(t, x[:, STATE.r][:, 1], "g-", label="y (m)")
    axes[0].plot(t, x[:, STATE.r][:, 2], "b-", label="z (m)")
    axes[0].axhline(1.0, color="k", linestyle="--", label="setpoint")
    axes[0].set_ylabel("Position (m)")
    axes[0].legend()
    axes[0].grid(visible=True)
    axes[0].set_title("Position Tracking")

    # Plot attitude from quaternion. Convert to Euler.
    from spacecraft.frames import euler_from_quaternion
    from spacecraft.quaternion import Quaternion

    euler_angles = np.array([euler_from_quaternion(Quaternion.from_array(q)) for q in x[:, STATE.q]])
    axes[1].plot(t, np.rad2deg(euler_angles[:, 1]), "r-", label="roll (deg)")
    axes[1].plot(t, np.rad2deg(euler_angles[:, 0]), "g-", label="pitch (deg)")
    axes[1].plot(t, np.rad2deg(euler_angles[:, 2]), "b-", label="yaw (deg)")
    axes[1].set_ylabel("Attitude (deg)")
    axes[1].legend()
    axes[1].grid(visible=True)
    axes[1].set_title("Attitude")

    axes[2].plot(t, u[:, 0], "r-", label="Rotor 1")
    axes[2].plot(t, u[:, 1], "g-", label="Rotor 2")
    axes[2].plot(t, u[:, 2], "b-", label="Rotor 3")
    axes[2].plot(t, u[:, 3], "y-", label="Rotor 4")
    axes[2].set_xlabel("Time (s)")
    axes[2].set_ylabel("Thrust (N)")
    axes[2].legend()
    axes[2].grid(visible=True)
    axes[2].set_title("Rotor Commands")

    fig.tight_layout()
    plt.gca()
    return


if __name__ == "__main__":
    app.run()
